### ISSUE TITLE
WinMerge causing leftover garbage files

### ISSUE THREAD

**Issue by mmikeww** [kujotx/chocolatey-packages#10]
Clean win10 install. Installed chocolatey. Then `choco install winmerge` and I'm getting these garbage files in the root C:\ folder:

https://support.microsoft.com/en-us/help/950683/vcredist-from-vc-2008-installs-temporary-files-in-root-directory

`choco uninstall winmerge` removes these files

This issue also describes it:
https://github.com/chocolatey/chocolatey-coreteampackages/issues/724

**Comment by mmikeww** [comment]
I just downloaded the exe installer directly from the WinMerge site, and that too causes these garbage files.  So I guess its not a chocolatey problem

**Comment by majkinetor** [comment]
Yet chocolatey can clean it. I'll see what I can do.

**Comment by kujotx** [comment]
Cleaning up unresolved issues. Closing as this was resolved by chocolatey.
