### ISSUE TITLE
Upgrade to Wireshark 2.6.2

### ISSUE THREAD

**Issue by rgl** [kujotx/chocolatey-packages#12]
Can you please upgrade to Wireshark 2.6.2?

**Comment by rgl** [comment]
also because https://1.na.dl.wireshark.org/win64/Wireshark-win64-2.6.1.exe is not available anymore (returns 404).

**Comment by rgl** [comment]
maybe we should download from https://www.wireshark.org/download/win64/all-versions/ instead.

**Comment by kujotx** [comment]
I just got chron abilities on appveyor, so I will set this up to auto build. 

Also, I'll check the links with the Wireshark team to see what's preferable.

Thanks.
