### ISSUE TITLE
2.2.4 released on 24-Jan-17

### ISSUE THREAD

**Issue by rasa** [kujotx/chocolatey-packages#8]
See https://www.wireshark.org/#group_873

**Comment by kujotx** [comment]
My apologies.

It appears me service is not running reliably. I will take a look at this later and update it manually.

I have been looking at switching the automated testing, under which my packages currently run, to the new [au project](https://github.com/majkinetor/au) method.

Thanks for the head's up.

**Comment by rasa** [comment]
No worries. Thanks for maintaining this!
