### ISSUE TITLE
Wireshark Download link 2.2.6 Invalid

### ISSUE THREAD

**Issue by beufordy3k** [kujotx/chocolatey-packages#9]
Chocolatey Package for Wireshark 2.2.6 points to [https://1.na.dl.wireshark.org/win64/Wireshark-win64-2.2.6.exe](https://1.na.dl.wireshark.org/win64/Wireshark-win64-2.2.6.exe) this link experiences a timeout and a zero byte file is written, thus the sha256 checksum validation fails and the chocolatey install aborts.

The link per the official wireshark download page (https://www.wireshark.org/download.html) is,
[https://2.na.dl.wireshark.org/win64/Wireshark-win64-2.2.6.exe](https://2.na.dl.wireshark.org/win64/Wireshark-win64-2.2.6.exe) which, when downloaded directly via a browser does result in a sha256 hash matching the expected,

![image](https://cloud.githubusercontent.com/assets/4059486/25689833/6a96328c-3059-11e7-9749-e841d9158aef.png)

Please update the chocolatey package accordingly.

Thanks!

**Comment by kujotx** [comment]
Actually, the Wireshark team instructed me to use that server. It was likely down when you made your request. Closing this issue.
